"""add webhook events table

Revision ID: 7cf13c899d2b
Revises: 2c655ad6e487
Create Date: 2025-01-29 22:41:05.756799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf13c899d2b'
down_revision: Union[str, None] = '2c655ad6e487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_events_processed_at', 'webhook_events', ['processed_at'], unique=False)
    op.create_index('ix_webhook_events_type', 'webhook_events', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_events_type', table_name='webhook_events')
    op.drop_index('ix_webhook_events_processed_at', table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
