"""add failed webhook events table

Revision ID: 8d533225d254
Revises: 7cf13c899d2b
Create Date: 2025-01-29 23:07:26.138251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d533225d254'
down_revision: Union[str, None] = '7cf13c899d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('webhook_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('last_retry', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_failed_webhook_events_status', 'failed_webhook_events', ['status'], unique=False)
    op.create_index('ix_failed_webhook_events_webhook_id', 'failed_webhook_events', ['webhook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_failed_webhook_events_webhook_id', table_name='failed_webhook_events')
    op.drop_index('ix_failed_webhook_events_status', table_name='failed_webhook_events')
    op.drop_table('failed_webhook_events')
    # ### end Alembic commands ###
